AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution

Parameters:
  StackNamePrefix:
    Type: String
    Default: enpm818n
  DomainName:
    Type: String
    Description: Domain Name from Route 53
    Default: "carl-aws.com"
  AcmCertificateArn:
    Type: String

Resources:
  ############################
  # S3 Bucket OAC and Policy #
  ############################
  OriginAccessControlS3:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${StackNamePrefix}-assets-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: 
              - !Sub 
                  - '${BucketArn}/*'
                  - BucketArn: 
                      Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketArn'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution.Id}'

  # CloudFront fowards an IP chain to the app, need to isolate only the user's address
  OriginRequestPolicyWithIP:
    Type: AWS::CloudFront::OriginRequestPolicy
    Properties:
      OriginRequestPolicyConfig:
        Name: !Sub '${StackNamePrefix}-ip-and-all'
        CookiesConfig:
          CookieBehavior: "all"
        QueryStringsConfig:
          QueryStringBehavior: "all"
        HeadersConfig:
          HeaderBehavior: "whitelist"
          Headers:
            - "CloudFront-Viewer-Address"  # User's IP connected to CloudFront
            - "Host"  # Everything below is standard
            - "User-Agent"
            - "Referer"
            - "Accept"
            - "Accept-Language"

  ProductDetailsCachePolicy:
    Type: AWS::CloudFront::CachePolicy
    Properties:
      CachePolicyConfig:
        Name: 'Dynamic-Product-Details-Policy'
        DefaultTTL: 300  # seconds
        MaxTTL: 3600
        MinTTL: 0  
        ParametersInCacheKeyAndForwardedToOrigin:
          CookiesConfig:
            CookieBehavior: none
          HeadersConfig:
            HeaderBehavior: none
          QueryStringsConfig:
            QueryStringBehavior: whitelist
            QueryStrings:
              - 'product_id' # Cache based on product_id because add_to_cart is a GET request
          EnableAcceptEncodingGzip: true
          EnableAcceptEncodingBrotli: true

  ###########################
  # CloudFront Distribution #
  ###########################
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub '${StackNamePrefix}-CloudFront-Distribution'
        Aliases: 
          - !Ref DomainName
        PriceClass: PriceClass_100  # Cheap, NA/EU only
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        # Origin Definitions
        Origins:
          - Id: ALBOrigin
            DomainName:
              Fn::ImportValue: !Sub '${StackNamePrefix}-ALBDNSName'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
              OriginSSLProtocols: [TLSv1.2]

          - Id: S3Origin
            DomainName:
             Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketDomainName'
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt OriginAccessControlS3.Id

        OriginGroups:
          Quantity: 1
          Items:
            - Id: S3-Fail-Use-ALB-Group
              FailoverCriteria:
                StatusCodes:
                  Quantity: 2
                  Items: [403, 404]
              Members:
                Quantity: 2
                Items:
                  - OriginId: S3Origin
                  - OriginId: ALBOrigin

        # Default Behavior
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [HEAD, DELETE, POST, GET, OPTIONS, PUT, PATCH]
          CachedMethods: [HEAD, GET]
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad  # CachingDisabled
          OriginRequestPolicyId: !Ref OriginRequestPolicyWithIP
          Compress: true

        CacheBehaviors:
            ############################################
            # Important Note about products.php #
            ############################################
            # We CANNOT cache products because it makes a GET request for 'add_to_cart'

            # Static: Assets
          - PathPattern: 'assets/*'
            TargetOriginId: S3-Fail-Use-ALB-Group  # For good measure
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET, OPTIONS]
            CachedMethods: [HEAD, GET]
            CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6'  # CachingOptimized
            Compress: true
          
          # Static: Product images
          - PathPattern: 'admin/product_images/*'
            TargetOriginId: S3-Fail-Use-ALB-Group  # If a new product image is uploaded, it won't be in the S3 bucket
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET, OPTIONS]
            CachedMethods: [HEAD, GET]
            CachePolicyId: '658327ea-f89d-4fab-a63d-7e88639e58f6'  # CachingOptimized
            Compress: true

          # Dynamic: Limited scope on caching product_details, using ProductDetailsCachePolicy
          - PathPattern: 'product_details.php'
            TargetOriginId: ALBOrigin
            ViewerProtocolPolicy: redirect-to-https
            CachePolicyId: !Ref ProductDetailsCachePolicy
            OriginRequestPolicyId: !Ref OriginRequestPolicyWithIP
            Compress: true

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'  # Must end with a dot
      Name: !Ref DomainName
      Type: A  # IPv4 record
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  DistributionDomainName:
    Description: CloudFront URL
    Value: !GetAtt Distribution.DomainName