AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution

Parameters:
  StackNamePrefix:
    Type: String
    Default: enpm818n
  DomainName:
    Type: String
    Description: Domain Name from Route 53
    Default: "carl-aws.com"
  AcmCertificateArn:
    Type: String

Resources:
  ##########################
  # Origin Access Controls #
  ##########################
  OriginAccessControlS3:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${StackNamePrefix}-assets-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ###########################
  # CloudFront Distribution #
  ###########################
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CDN for ${StackNamePrefix} static assets'
        Aliases: 
          - !Ref DomainName
        PriceClass: PriceClass_100  # Cheap, NA/EU only
        HttpVersion: http2
        ViewerCertificate:
          AcmCertificateArn: !Ref AcmCertificateArn
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1.2_2021

        # Origin Definitions
        Origins:
          - Id: ALBOrigin
            DomainName:
              Fn::ImportValue: !Sub '${StackNamePrefix}-ALBDNSName'
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: https-only 
              OriginSSLProtocols: [TLSv1.2]

          - Id: S3Origin
            DomainName:
             Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketDomainName'
            S3OriginConfig: {}
            OriginAccessControlId: !GetAtt OriginAccessControlS3.Id

        # Default Behavior
        DefaultCacheBehavior:
          TargetOriginId: ALBOrigin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [HEAD, DELETE, POST, GET, OPTIONS, PUT, PATCH]
          CachedMethods: [HEAD, GET]
          Compress: true
          CachePolicyId: 4135ea2d-6df8-44a3-9df3-4b5a84be39ad
          OriginRequestPolicyId: 216adef6-5c7f-47e4-b989-5492eafa07d3

        # Cache static assets in S3 bucket
        CacheBehaviors:
          - PathPattern: '*.jpg'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET, OPTIONS]
            CachedMethods: [HEAD, GET]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

          - PathPattern: '*.png'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET, OPTIONS]
            CachedMethods: [HEAD, GET]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

          - PathPattern: '*.css'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET, OPTIONS]
            CachedMethods: [HEAD, GET]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

          - PathPattern: '*.js'
            TargetOriginId: S3Origin
            ViewerProtocolPolicy: redirect-to-https
            AllowedMethods: [HEAD, GET, OPTIONS]
            CachedMethods: [HEAD, GET]
            Compress: true
            CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6

  #############################################
  # S3 Bucket Policy allowing CF Distribution #
  #############################################
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: 
              - !Sub 
                  - '${BucketArn}/*'
                  - BucketArn: 
                      Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketArn'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution.Id}'

  RecordSet:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub '${DomainName}.'  # Must end with a dot
      Name: !Ref DomainName
      Type: A  # IPv4 record
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

Outputs:
  DistributionDomainName:
    Description: CloudFront URL
    Value: !GetAtt Distribution.DomainName