AWSTemplateFormatVersion: '2010-09-09'
Description: CloudFront Distribution

Parameters:
  StackNamePrefix:
    Type: String
    Default: enpm818n

Resources:
  ##########################
  # Origin Access Controls #
  ##########################
  OriginAccessControlS3:
    Type: AWS::CloudFront::OriginAccessControl
    Properties:
      OriginAccessControlConfig:
        Name: !Sub '${StackNamePrefix}-assets-oac'
        OriginAccessControlOriginType: s3
        SigningBehavior: always
        SigningProtocol: sigv4

  ###########################
  # CloudFront Distribution #
  ###########################
  Distribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Enabled: true
        Comment: !Sub 'CDN for ${StackNamePrefix} static assets'
        PriceClass: PriceClass_100  # Cheap, NA/EU only
        HttpVersion: http2
        Origins:
          - Id: S3Origin
            DomainName: 
              Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketDomainName'
            OriginAccessControlId: !GetAtt OriginAccessControlS3.Id
            S3OriginConfig: {}
        DefaultCacheBehavior:
          TargetOriginId: S3Origin
          ViewerProtocolPolicy: redirect-to-https
          AllowedMethods: [GET, HEAD, OPTIONS]
          CachedMethods: [GET, HEAD, OPTIONS]
          CachePolicyId: 658327ea-f89d-4fab-a63d-7e88639e58f6
          Compress: true  # gzip compression

  #############################################
  # S3 Bucket Policy allowing CF Distribution #
  #############################################
  BucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: 
        Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketName'
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Sid: AllowCloudFrontServicePrincipal
            Effect: Allow
            Principal:
              Service: cloudfront.amazonaws.com
            Action: s3:GetObject
            Resource: 
              - !Sub 
                  - '${BucketArn}/*'
                  - BucketArn: 
                      Fn::ImportValue: !Sub '${StackNamePrefix}-S3BucketArn'
            Condition:
              StringEquals:
                AWS:SourceArn: !Sub 'arn:aws:cloudfront::${AWS::AccountId}:distribution/${Distribution.Id}'

Outputs:
  DistributionDomainName:
    Description: CloudFront URL
    Value: !GetAtt Distribution.DomainName
    Export:
      Name: !Sub '${StackNamePrefix}-DistributionDomainName'